export const projects = [
  {
    title: 'Digital Media Agency',
    description: "Using Html,Css and Javascript i made This MasterPiece A great website eye appealing with Slider And good animations",
      // image: '/images/1.png',
      tags: ['Html', 'Css', 'Javascript', 'Sass'],
    source: 'https://github.com/TarekHassan1/Digital-media-Agency-Website',
    visit: 'https://tarekhassan1.github.io/Digital-media-Agency-Website/',
    id: 0,
  },
  {
    title: 'Seo Master Website',
    description:"Seo Master website is a website built on html javascript and tailwincss",
    // image: '/images/2.png',
    tags: ['html',"tailwindcss","css", 'JavaScript'],
    source: 'https://github.com/TarekHassan1/Tailwind-Based-Website',
    visit: 'https://tarekhassan1.github.io/Tailwind-Based-Website/',
    id: 1,
  },
  {
    title: 'chain app  website',
    description: "chain app  website is a Modern website built on reactJs",
      // image: '/images/3.jpg',
      tags: ['React', 'javscript',"html","Tailwindcss","css"],
    source: 'https://github.com/TarekHassan1/chain-app-dev-website-in-react',
    visit: 'https://tarekhassan1.github.io/chain-app-dev-website-in-react/',
    id: 2,
  },
  {
    title: 'Fit Club website',
    description: "this is a fitness Website Build on reactjs",
    // image: '/images/4.jpg',
    tags: ['React', 'Javascript', 'Html',"css"],
    source: 'https://github.com/TarekHassan1/fit-club',
    visit: 'https://tarekhassan1.github.io/fit-club/',
    id: 3,
  },
  {
    title: 'Hang Man Game',
    description: "this is a word guessing game",
    // image: '/images/5.jpg',
    tags: ['typescript', 'Javascript', 'Html',"css"],
    source: 'https://github.com/TarekHassan1/HangManGame-inTypeScript',
    visit: 'https://tarekhassan1.github.io/HangManGame-inTypeScript/',
    id: 4,
  },
  {
    title: 'Typing Speed Test',
    description: "this is the Typing Test app",
    // image: '/images/6.png',
    tags: [ 'Javascript', 'Html',"css"],
    source: 'https://github.com/TarekHassan1/typing-speed-test',
    visit: 'https://tarekhassan1.github.io/typing-speed-test/',
    id: 5,
  },
  {
    title: 'MineSweeper Game in Javascript',
    description: "This is the MineSweeper Game",
    // image: '/images/7.jpg',
    tags: [ 'Javascript', 'Html',"css"],
    source: 'https://github.com/TarekHassan1/mineSweeper-in-javascript',
    visit: 'https://tarekhassan1.github.io/mineSweeper-in-javascript/',
    id: 6,
  },
];

export const TimeLineData = [
  { year: 2022, text: 'Started my journey And Learned C++ and Data Structuers and algorthims', },
  { year: 2023, text: 'Learned Html | CSS | Tailwindcss | sass | pugjs |  react | nextjs', },
  { year: "2023/6/6", text: 'Completed Over 30 Projects!', },
];